field: 661f0cbe-8667-4984-aea8-55239d2f6e8e # Body builder
fieldLayouts:
  a0b73357-c352-4da0-a14f-23235c80fa59:
    tabs:
      -
        elements:
          -
            fieldUid: ee12cfc1-e007-4254-bc36-f5ff21ea00bd # Body
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: 4d75c350-59e2-4ecc-b469-bb97f6ff276d # Section background colour
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
        name: Content
        sortOrder: 1
fields:
  4d75c350-59e2-4ecc-b469-bb97f6ff276d: # Section background colour
    columnSuffix: null
    contentColumnType: string
    fieldGroup: null
    handle: sectionBG
    instructions: ''
    name: 'Section background colour'
    searchable: false
    settings:
      optgroups: true
      options:
        -
          __assoc__:
            -
              - label
              - White
            -
              - value
              - white
            -
              - default
              - '1'
        -
          __assoc__:
            -
              - label
              - Silver
            -
              - value
              - silver
            -
              - default
              - ''
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\Dropdown
  ee12cfc1-e007-4254-bc36-f5ff21ea00bd: # Body
    columnSuffix: null
    contentColumnType: text
    fieldGroup: null
    handle: body
    instructions: ''
    name: Body
    searchable: true
    settings:
      availableTransforms: '*'
      availableVolumes: ''
      columnType: text
      configSelectionMode: choose
      defaultTransform: ''
      manualConfig: ''
      purifierConfig: ''
      purifyHtml: '1'
      redactorConfig: Simple.json
      removeEmptyTags: '1'
      removeInlineStyles: '1'
      removeNbsp: '1'
      showHtmlButtonForNonAdmins: ''
      showUnpermittedFiles: false
      showUnpermittedVolumes: false
      uiMode: normal
    translationKeyFormat: null
    translationMethod: none
    type: craft\redactor\Field
handle: text
name: Text
sortOrder: 1
