dateModified: 1602332861
email:
  fromEmail: james@cld.agency
  fromName: Boilerplate
  transportType: craft\mail\transportadapters\Sendmail
fieldGroups:
  1ea64795-1fc7-49cb-994f-d8b875b4b1cb:
    name: Common
siteGroups:
  fcaa7f55-bc86-4e20-b6e6-7cbb722f0dde:
    name: Boilerplate
sites:
  345898ee-6fda-4b37-8936-22247a55ae36:
    baseUrl: $DEFAULT_SITE_URL
    handle: default
    hasUrls: true
    language: en-GB
    name: Boilerplate
    primary: true
    siteGroup: fcaa7f55-bc86-4e20-b6e6-7cbb722f0dde
    sortOrder: 1
system:
  edition: solo
  live: true
  name: Boilerplate
  schemaVersion: 3.4.10
  timeZone: America/Los_Angeles
users:
  allowPublicRegistration: false
  defaultGroup: null
  photoSubpath: ''
  photoVolumeUid: null
  requireEmailVerification: true
